version: "3.8"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  ipfs:
    image: ipfs/go-ipfs
    command: ["daemon", "--migrate=true"]
    ports:
      - "5001:5001"
      - "8080:8080"
      - "4001:4001"
    volumes:
      - ipfs-data:/data/ipfs
    networks:
      - app-network

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    entrypoint: ["cd app && npx prisma generate && npx prisma db push && npm run deploy:prod"]
    depends_on:
      - db
      - redis
      - ipfs

volumes:
  ipfs-data:
  redis-data:
  db-data:
  letsencrypt:

networks:
  app-network:
