version: "3.8"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    command: [ "redis-server", "--requirepass", "mypassword", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  ipfs-data:
  redis-data:
  db-data:

networks:
  app-network:
