version: "3.8"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  ipfs:
    image: ipfs/go-ipfs
    command: ["daemon", "--migrate=true"]
    ports:
      - "5001:5001"
      - "8080:8080"
      - "4001:4001"
    volumes:
      - ipfs-data:/data/ipfs
    networks:
      - app-network

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  nginx:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      CERTBOT_EMAIL: "sunsuking@gmail.com"
      CERTBOT_DOMAIN: "mybling.social"
    volumes:
      - ./conf.d:/etc/conf.d/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod.prod
    restart: unless-stopped

volumes:
  ipfs-data:
  redis-data:
  db-data:

networks:
  app-network:
