import type { NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "../components/layout";
import { useRouter } from "next/navigation";
import src from "@public/exam2.png";
import HeartIcon from "@components/icons/HeartIcons";
import HeartFillIcon from "@components/icons/HeartFillIcon";
import Link from "next/link";
import UserAvatar from "@/components/UserAvatar";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <Layout>
      <Head>
        <title>mybling | 마블링</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" grid-cols-1 space-y-7 p-5">
        {/* 게시글 */}
        <section className="m-0 bg-white grid-cols-1 justify-center items-center space-y-3">
          {/* top */}
          <div className="flex justify-between pr-3">
            {/* 프로필 */}
            <UserAvatar />
            {/* 좋아요 수*/}
            <div className="flex items-center space-x-1">
              <HeartIcon />
              <span>999+</span>
            </div>
          </div>
          {/* 썸네일 */}
          <div className="flex items-center justify-center aspect-square bg-gray-300 rounded-3xl">
            {/* 링크에 /posts치기 귀찮아서 임의로 넣은 link tag🫵🏾 */}
            <Link href="/posts">
              <Image src={src} alt="post"></Image>
            </Link>
          </div>
          {/* 게시글 내용(bottom) */}
          <div>
            <p className="text-sm">
              마지심슨이 책을 읽고 있습니다. 이 책은 마지심슨이 읽고 있는 책은
              &apos;모든 것에 대한 해답&apos;이라는 제목의 자기계발..
            </p>
          </div>
        </section>
        {/* 게시글 */}
        <section className="m-0 bg-white grid-cols-1 justify-center items-center space-y-3">
          {/* top */}
          <div className="flex justify-between pr-3">
            {/* 프로필 */}
            <UserAvatar />
            {/* 좋아요 수*/}
            <div className="flex items-center space-x-1">
              <HeartIcon />
              <span>999+</span>
            </div>
          </div>
          {/* 썸네일 */}
          <div className="flex items-center justify-center aspect-square bg-gray-300 rounded-3xl">
            <Image src={src} alt="post"></Image>
          </div>
          {/* 게시글 내용(bottom) */}
          <div>
            <p className="text-sm">
              마지심슨이 책을 읽고 있습니다. 이 책은 마지심슨이 읽고 있는 책은
              &apos;모든 것에 대한 해답&apos;이라는 제목의 자기계발..
            </p>
          </div>
        </section>
      </div>
    </Layout>
  );
};

export default Home;
