import type { NextPage } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/layout";
import Link from "next/Link";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
const Home: NextPage = () => {
  const router = useRouter();
  return (
    <Layout hasTabBar>
      <Head>
        <title>mybling | 마블링</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={"border-y-2 mt-24"}>
        <h1 className={"text-3xl font-bold underline underline-offset-1"}>
          캡스톤 하준 브랜치 입니당.
        </h1>
      </section>
      <>
        <button
          className="p-8 rounded-3xl bg-rose-300 border-double border-4 border-sky-500"
          onClick={() => {
            router.push("/posts");
          }}
        >
          post페이지 이동하기 (임시버전)
        </button>
      </>
    </Layout>
  );
};

export default Home;
